{{- if .Values.containerSensor.clusterRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: darktrace-containersensor-pod-reader
  labels:
    {{- include "containersensor.labels" . | nindent 4 }}
  {{- if .Values.containerSensor.annotations }}
  annotations: 
    {{ .Values.containerSensor.annotations | toYaml }}
  {{- end }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "replicationcontrollers"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "replicasets", "daemonsets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "watch", "list"]
{{- end }}
