{{- if .Values.containerSensor.clusterRoleBinding.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: darktrace-containersensor-pod-reader
  labels:
    {{- include "containersensor.labels" . | nindent 4 }}
  {{- if .Values.containerSensor.annotations }}
  annotations: 
    {{ .Values.containerSensor.annotations | toYaml }}
  {{- end }}
subjects:
- kind: ServiceAccount 
  namespace: {{ .Release.Namespace }}
  name: darktrace-containersensor
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: darktrace-containersensor-pod-reader 
  apiGroup: rbac.authorization.k8s.io
{{- end }}
