{{- if .Values.containerSensor.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: darktrace-containersensor-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "containersensor.labels" . | nindent 4 }}
  {{- if .Values.containerSensor.annotations }}
  annotations: 
    {{ .Values.containerSensor.annotations | toYaml }}
  {{- end }}
data:
  {{- if .Values.containerSensor.secret.overrideValue }}
  token: {{ .Values.containerSensor.secret.overrideValue | b64enc }}
  {{- else }}
  token: {{ .Values.vSensorHmacKey | b64enc }}
  {{- end }}
{{- end }}
