{{- if .Values.containerSensor.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: darktrace-containersensor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "containersensor.labels" . | nindent 4 }}
  {{- if .Values.containerSensor.annotations }}
  annotations: 
    {{ .Values.containerSensor.annotations | toYaml }}
  {{- end }}
{{- end }}
