{{- if .Values.osSensor.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: darktrace-ossensor-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "containersensor.labels" . | nindent 4 }}
  {{- if .Values.osSensor.annotations }}
  annotations: 
    {{ .Values.osSensor.annotations | toYaml }}
  {{- end }}
data:
  VSENSOR_HMAC_KEY: {{ .Values.vSensorHmacKey | b64enc }}
{{- end }}
